### ISSUE TITLE
Ansible Warning about CONDITIONAL_BARE_VARS

### ISSUE THREAD

**Issue by kakawait** [gantsign/ansible-role-java#191]
```
[DEPRECATION WARNING]: evaluating java_is_default_installation as a bare 
variable, this behaviour will go away and you might need to add |bool to the 
expression in the future. Also see CONDITIONAL_BARE_VARS configuration toggle..
 This feature will be removed in version 2.12. Deprecation warnings can be 
disabled by setting deprecation_warnings=False in ansible.cfg.
```

We may fix it?

**Comment by freemanjp** [comment]
@kakawait thanks for raising this issue.

I'm waiting for the 2.22 release of [Molecule](https://github.com/ansible/molecule) (the test framework I'm using), so I can test against Ansible 2.8 (introduced this deprecation warning), before fixing this issue.

**Comment by kakawait** [comment]
I saw the same issue on maven role. Should I report it too or you'll do batch fix ?

**Comment by freemanjp** [comment]
It's a problem on most of my roles, I'll batch fix them once the new version of Molecule is released. The deprecation warning will cause a test failure, so updating Ansible & Molecule across my roles will catch any that need fixing. As irritating as the deprecation warning is, it'll be over a year before they actually change the behaviour, so there's time.

**Comment by kakawait** [comment]
Yeah yeah no problem. I have same on my own role. I'll not rush update haha. Take your time. I just wanted to notice you because I'm using your java role today (is great) and i saw those warnings

**Comment by freemanjp** [comment]
Thanks, I'm glad you find it useful and thanks for taking the time to report the issue.

**Comment by freemanjp** [comment]
@kakawait the Ansible team have made this warning more selective in their [2.8.2](https://github.com/ansible/ansible/blob/stable-2.8/changelogs/CHANGELOG-v2.8.rst#bugfixes) release and this role no longer receives the warning, so I'm closing this issue.

**Comment by kakawait** [comment]
@freemanjp Nice.

Currently I'm stuck on 2.7 Ansible due to blocking regression bug on 2.8 that is not yet fixed. But I'm sure the warning is no more if you said it :)
