### ISSUE TITLE
AdoptOpenJDK v2 API deprecated

### ISSUE THREAD

**Issue by getjack** [gantsign/ansible-role-java#214]
I tried to use the version 8.2.0 of your role but got a 404 error when calling https://api.adoptopenjdk.net/v2/info/releases/openjdk11?openjdk_impl=hotspot&os=linux&arch=x64&release=latest&type=jdk&heap_size=normal in the ansible task. The api news state that the v2 API of https://api.adoptopenjdk.net/ is deprecated and may have been already removed.

Edit: Seems like they had a minor downtime. However, this role should still migrate to v3

**Comment by freemanjp** [comment]
@getjack thanks for reporting this issue you can find the change in version [9.0.0](https://github.com/gantsign/ansible-role-java/releases/tag/9.0.0) of this role.
