### ISSUE TITLE
Script fails on RHEL7

### ISSUE THREAD

**Issue by dedayoa** [gantsign/ansible-role-java#247]
While running this script in RHEL 7, it fails at

TASK [gantsign.java : generate CDS archive] **********************************************************
fatal: [192.168.1.84]: FAILED! => {"changed": false, "cmd": "/opt/java/jdk-9.0.4+11/bin/java -Xshare:dump", "msg": "[Errno 2] No such file or directory", "rc": 2}

The task before that...which exposes java_jdk_layout.rc...
TASK [gantsign.java : check JDK archive layout] ******************************************************
ok: [192.168.1.84] => {"changed": false, "cmd": "set -o pipefail\ntar --list --file /root/.ansible/tmp/downloads/OpenJDK9U-jdk_x64_linux_hotspot_9.0.4_11.tar.gz | grep --quiet '^\\.'\n", "delta": "0:00:00.008718", "end": "2021-05-04 09:15:13.128682", "failed_when_result": false, "msg": "non-zero return code", **"rc": 141,** "start": "2021-05-04 09:15:13.119964", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

I was able to debug the cause down to https://github.com/gantsign/ansible-role-java/blob/bfdc94b92b51d6d7e21d326898b0b3c600948568/tasks/adoptopenjdk.yml#L104

I was able to get my install going by replacing with 
extra_opts:
      - "--strip-components={{ (java_jdk_layout.rc == 0) | ternary**('1', '2')** }}"

I've not dug into the code enough to see if this is a solution or just a workaround.

***
ansible-playbook 2.9.20
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Aug 13 2020, 02:51:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
***
Linux hostname 3.10.0-1160.25.1.el7.x86_64 #1 SMP Tue Apr 13 18:55:45 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux
***

**Comment by freemanjp** [comment]
Appears to be specific to the packaging of `jdk-9.0.4+11` (the first few releases from AdoptOpenJDK were sometimes inconsistent in their layout for tar files). I've removed mention of older non-LTS versions from the documentation. Closing as Oracle ended support for JDK 9 in March 2018.
