### ISSUE TITLE
Fail on RHEL8 

### ISSUE THREAD

**Issue by pun-ky** [gantsign/ansible-role-java#249]
```
TASK [gantsign.java : install dependencies (apt, yum, dnf, zypper)] ************
fatal: [aem]: FAILED! => {
    "changed": false,
    "rc": 1,
    "results": []
}

MSG:

Failed to synchronize cache for repo 'rhui-codeready-builder-for-rhel-8-x86_64-rhui-rpms'
```

it stopped working a few days ago. strange :/

I tried with rerunning, no effect. I am sure that I run the same playbook using your role a few days ago and it worked.

**Comment by krystian-panek-wttech** [comment]
to fix this problem it is needed to run:

```
sudo yum update -y yum dnf rpm 
```

before running Ansible

**Comment by freemanjp** [comment]
@pun-ky sorry for the late reply, my day job isn't leaving much time for OSS of late.

It's good practice for any Ansible playbook that installs OS packages, that you should add a task to the `pre_tasks` section of the playbook to update the OS package index. While you could in theory add it to roles like this, it would slow your provisioning down if multiple roles updated the package index, you may also get temporally blocked if you download the package index too frequently (which would cause provisioning to fail).

So, I'm not going to change this role, but thanks for raising this issue so others have this advice in case they encounter the same issue.
