### ISSUE TITLE
Request: Java NOT support AARCH64(ARM64) 

### ISSUE THREAD

**Issue by prowessandy** [gantsign/ansible-role-java#303]
Hi authors, 

As we are adopting AWS m6g instances instead of the traditional m5 ones, we have to run the deployment pipeline in Ansible with all ARM64/AARCH64 supported roles. Currently, our JAVA(Adoptopenjdk) right fails at this role stating it doesn't support Aarch64. Any possibility to carry this through or add it to your development roadmap? Thanks so much!

**Comment by freemanjp** [comment]
Hi @prowessandy, the role does actually have undocumented support for aarch64, just add `java_arch: aarch64` as an Ansible variable for the role.

You're actually the first person to request aarch64 support. When I get time I'll add architecture auto-detection and a test for aarch64.

**Comment by prowessandy** [comment]
Hi @freemanjp, thanks for getting back to me. We've tested the role in our pipeline with Ansible, which gave the explicit error that 'aarch64 is not supported.'

We have been using this beautiful role for years, no problem. But as the powerful yet cheaper m6g EC2 class went GA, we'll have to follow the business decision to introduce new customers onto m6g. The main blocker is exactly the JAVA installation. Appreciate your effort to help make it happen ASAP :)

**Comment by freemanjp** [comment]
Hi @prowessandy, sorry for the delay. Support for AArch64 is now included in version [11.1.0](https://github.com/gantsign/ansible-role-java/releases/tag/11.1.0) of this role.

I don't know where the error "aarch64 is not supported" originated from, so I'm not sure this change will solve the error you're seeing. This role now includes tests that verify it works on AArch64 (#306). The problem may be somewhere else in your stack.

**Comment by prowessandy** [comment]
Thanks John, it did work before today's commit but only if java_arch:
aarch64 is defined in our Ansible files.
