### ISSUE TITLE
Does not work with Ansible 7.3.0 

### ISSUE THREAD

**Issue by krystian-panek-wttech** [gantsign/ansible-role-java#321]
<img width="1073" alt="image" src="https://user-images.githubusercontent.com/81212505/224687611-632ecb24-94d0-400c-aa06-57a052b5ab25.png">

I just upgraded Ansible from 5.x to the most recent and unexpectedly one of the tasks from your role failed.

**Comment by freemanjp** [comment]
@krystian-panek-wttech thanks for reporting this issue, you can find the fix in version [11.1.3](https://github.com/gantsign/ansible-role-java/releases/tag/11.1.3) of this role.
