### ISSUE TITLE
is there a way to specify not to install if JAVA is already installed?

### ISSUE THREAD

**Issue by yogeshVU** [gantsign/ansible-role-java#86]
is there a way to specify not to install if JAVA is already installed?

**Comment by freemanjp** [comment]
Sorry, for the late reply:

There isn't a built in way for this role to skip the install if another copy of Java is already installed; given the whole DevOps approach is all about getting environments in a reliable and predictable state, putting this conditional login in the role would mean you wouldn't be certain what the resulting Java version would be after it is run; for that reason I've no plans to add such conditional logic to the role.

My advice would be to use Ansible tags to control, which role is used to install Java (i.e. this role or the other role which you're using that installs Java).

If you really need to run this role conditionally, based on detecting whether Java is installed, execute a shell command for `java -version` bind the result to a variable using `register` and conditionally execute this role using `when`: https://docs.ansible.com/ansible/playbooks_conditionals.html
